In [31]:
import torch
import torch.nn as nn

# set number of significant digits to print out
torch.set_printoptions(precision=10)
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, -5.0, 6.0], [20.0, 10.0, -30.0], [-3.0, 2.0, 31.0]], dtype=torch.float32)
x.requires_grad = True
bn = nn.BatchNorm1d(3, dtype=torch.float32)
result = bn(x)
t = result.tanh()
loss = t.sum()
print(loss)
loss.backward()
print(x.grad)

tensor(-0.3947991729, grad_fn=<SumBackward0>)
tensor([[ 0.0110761188,  0.0737276152,  0.0182866342],
        [ 0.0410607755, -0.0786427706,  0.0167493112],
        [-0.0144230416, -0.0688124299, -0.0152583374],
        [-0.0377138406,  0.0737276152, -0.0197776090]])


In [42]:
import torch
import torch.nn as nn
torch.set_printoptions(precision=10)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=torch.float32)
x.requires_grad = True
bn = nn.BatchNorm1d(2, dtype=torch.float32)
bn.weight.retain_grad()
bn.bias.retain_grad()
result = bn(x)
print(result)
loss = result.sum()
loss.backward()
print(bn.weight.grad)
print(bn.bias.grad)

tensor([[-1.2247426510e+00, -1.2247425318e+00],
        [-5.9604644775e-08,  0.0000000000e+00],
        [ 1.2247424126e+00,  1.2247425318e+00]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([0., 0.])
tensor([3., 3.])
